/**
 * Generates workbench/generated/registry.ts.
 *
 * The Angular CLI builds with esbuild, which has no `import.meta.glob`, so the
 * set of showcases has to exist as static source. Each entry keeps its
 * `id`/`group`/`title` inline and its module behind a dynamic `import()`, so
 * the sidebar renders the whole tree from one small module while every
 * showcase - and the library code it pulls in - stays a lazy chunk.
 *
 * Runs on Node's native type stripping (`node scripts/build-showcase-registry.ts`),
 * so it must stay erasable syntax. `npm run scripts:typecheck` enforces that.
 */
import fs from "node:fs";
import path from "node:path";
import process from "node:process";

import ts from "typescript";

const REPO_ROOT = path.resolve(import.meta.dirname, "..");
const OUTPUT_FILE = path.join(REPO_ROOT, "workbench", "generated", "registry.ts");
const SHOWCASE_SUFFIX = ".showcase.ts";
const SKIPPED_DIRECTORIES = new Set(["node_modules", "dist", "dist-workbench", ".git", ".angular", "storybook-static"]);

interface ShowcaseMeta {
  readonly id: string;
  readonly group: string;
  readonly title: string;
  readonly order: number;
  /** Module specifier, relative to the generated file, without extension. */
  readonly importPath: string;
  /** Repo-relative source path, for error messages. */
  readonly sourcePath: string;
}

function findShowcaseFiles(directory: string, found: string[] = []): string[] {
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const absolute = path.join(directory, entry.name);

    if (entry.isDirectory()) {
      if (!SKIPPED_DIRECTORIES.has(entry.name)) {
        findShowcaseFiles(absolute, found);
      }
      continue;
    }

    if (entry.isFile() && entry.name.endsWith(SHOWCASE_SUFFIX)) {
      found.push(absolute);
    }
  }

  return found;
}

/** Pulls the literal `id`/`group`/`title`/`order` out of `defineShowcase({ ... })`. */
function readShowcaseMeta(absolutePath: string): ShowcaseMeta {
  const sourcePath = path.relative(REPO_ROOT, absolutePath).split(path.sep).join("/");
  const source = ts.createSourceFile(absolutePath, fs.readFileSync(absolutePath, "utf8"), ts.ScriptTarget.Latest, true);

  let literal: ts.ObjectLiteralExpression | undefined;

  const visit = (node: ts.Node): void => {
    if (
      literal === undefined &&
      ts.isCallExpression(node) &&
      ts.isIdentifier(node.expression) &&
      node.expression.text === "defineShowcase" &&
      node.arguments.length > 0 &&
      node.arguments[0] !== undefined &&
      ts.isObjectLiteralExpression(node.arguments[0])
    ) {
      literal = node.arguments[0];
      return;
    }

    ts.forEachChild(node, visit);
  };

  visit(source);

  if (literal === undefined) {
    throw new Error(`${sourcePath}: no defineShowcase({ ... }) call found.`);
  }

  // Bound to a const so the narrowing survives the closures below.
  const properties = literal.properties;

  const readProperty = (name: string): ts.Expression | undefined => {
    for (const property of properties) {
      if (ts.isPropertyAssignment(property) && ts.isIdentifier(property.name) && property.name.text === name) {
        return property.initializer;
      }
    }

    return undefined;
  };

  const readString = (name: string): string => {
    const value = readProperty(name);

    if (value === undefined || !ts.isStringLiteralLike(value)) {
      throw new Error(`${sourcePath}: defineShowcase needs a literal string "${name}".`);
    }

    return value.text;
  };

  const orderNode = readProperty("order");
  const order = orderNode !== undefined && ts.isNumericLiteral(orderNode) ? Number(orderNode.text) : 0;

  const importPath = path
    .relative(path.dirname(OUTPUT_FILE), absolutePath)
    .split(path.sep)
    .join("/")
    .replace(/\.ts$/, "");

  return {
    id: readString("id"),
    group: readString("group"),
    title: readString("title"),
    order,
    importPath: importPath.startsWith(".") ? importPath : `./${importPath}`,
    sourcePath,
  };
}

function assertUniqueIds(entries: readonly ShowcaseMeta[]): void {
  const seen = new Map<string, string>();

  for (const entry of entries) {
    const previous = seen.get(entry.id);

    if (previous !== undefined) {
      throw new Error(`Duplicate showcase id "${entry.id}" in ${previous} and ${entry.sourcePath}.`);
    }

    seen.set(entry.id, entry.sourcePath);
  }
}

function renderRegistry(entries: readonly ShowcaseMeta[]): string {
  const rows = entries.map(
    (entry) => `  {
    id: ${JSON.stringify(entry.id)},
    group: ${JSON.stringify(entry.group)},
    title: ${JSON.stringify(entry.title)},
    order: ${entry.order},
    load: () => import(${JSON.stringify(entry.importPath)}),
  },`,
  );

  return `// Generated by scripts/build-showcase-registry.ts - do not edit.
// Run \`npm run workbench:registry\` to regenerate.
import type { RegistryEntry } from '../core/registry';

export const SHOWCASE_REGISTRY: readonly RegistryEntry[] = [
${rows.join("\n")}
];
`;
}

function build(): number {
  const entries = findShowcaseFiles(REPO_ROOT)
    .map(readShowcaseMeta)
    .sort((left, right) => {
      if (left.group !== right.group) {
        return left.group.localeCompare(right.group);
      }

      if (left.order !== right.order) {
        return left.order - right.order;
      }

      return left.title.localeCompare(right.title, undefined, {
        numeric: true,
      });
    });

  assertUniqueIds(entries);
  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, renderRegistry(entries), "utf8");

  return entries.length;
}

const count = build();
console.log(`workbench: registered ${count} showcase${count === 1 ? "" : "s"}.`);

if (process.argv.includes("--watch")) {
  let queued: NodeJS.Timeout | undefined;

  fs.watch(REPO_ROOT, { recursive: true }, (_event, filename) => {
    if (filename === null || !filename.endsWith(SHOWCASE_SUFFIX)) {
      return;
    }

    clearTimeout(queued);
    queued = setTimeout(() => {
      try {
        const rebuilt = build();
        console.log(`workbench: registry rebuilt (${rebuilt}).`);
      } catch (error) {
        console.error(`workbench: registry rebuild failed - ${(error as Error).message}`);
      }
    }, 50);
  });

  console.log("workbench: watching for *.showcase.ts changes.");
}
